---
# Copyright 2018, OpenNext SAS
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

- name: Deploy Elasticsearch  
  hosts: elasticsearch
  gather_facts: true
  user: root
  environment: "{{ onpc_environment_variables }}"
  pre-tasks:
    # Disable elasticsearch haproxy backend to avoid triggering false positive alerts.
    - include: /opt/openstack-ansible/playbooks/common-tasks/haproxy-endpoint-manage.yml
      vars:
        haproxy_backend: elasticsearch-back
        haproxy_state: disabled
      when:
        - "'elasticsearch' in group_names"
        - "groups['elasticsearch'] | length > 1"
    - include: "/opt/openstack-ansible/playbooks/common-tasks/os-{{ container_tech | default('lxc') }}-container-setup.yml"
      static: no
      vars:
        list_of_bind_mounts: "{{ elasticsearch_container_bind_mounts }}"
      tags: [elasticsearch, influxdb-install]
    - include: /opt/openstack-ansible/playbooks/common-tasks/os-log-dir-setup.yml
      vars:
        log_dirs:
          - src: "/openstack/log/{{ inventory_hostname }}-elasticsearch"
            dest: "{{ elasticsearch_log_dir }}"
      tags: [elasticsearch, influxdb-install]
  roles:
    - role: elasticsearch
    - role: "rsyslog_client"
      rsyslog_client_log_rotate_file: elaticsearch_log_rotate
      rsyslog_client_log_dir: "/var/log/elasticsearch"
      rsyslog_client_config_name: "99-elastic-rsyslog-client.conf"
      tags:
        - rsyslog
  post-tasks:
    # Enable back elasticsearch haproxy backend.
    - include: /opt/openstack-ansible/playbooks/common-tasks/haproxy-endpoint-manage.yml
      vars:
        haproxy_backend: elasticsearch-back
        haproxy_state: enabled
      when:
        - "'elasticsearch' in group_names"
        - "groups['elasticsearch'] | length > 1"
      tags: [elasticsearch, elasticsearch-rsyslog]
  
  vars_files:
    - vars/elasticsearch.yml
